### ISSUE TITLE
KeyError: AuthenticationResult

### ISSUE THREAD

**Issue by echoz** [sebirdman/hass_traeger#2]
Getting a `KeyError: AuthenticaitonResult` after entering my email and password to setup the integration.

Lemme know if there is anything else I can provide!

I installed the integration by adding a custom repo on HACS (https://hacs.xyz/) and installing it, restarting HASS thereafter.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/traeger/__init__.py", line 50, in async_setup_entry
    await client.start()
  File "/config/custom_components/traeger/traeger.py", line 217, in start
    await self.update_grills()
  File "/config/custom_components/traeger/traeger.py", line 111, in update_grills
    json = await self.get_user_data()
  File "/config/custom_components/traeger/traeger.py", line 78, in get_user_data
    await self.refresh_token()
  File "/config/custom_components/traeger/traeger.py", line 74, in refresh_token
    self.token_expires = response["AuthenticationResult"]["ExpiresIn"] + request_time
KeyError: 'AuthenticationResult'
```

**Comment by sebirdman** [comment]
@echoz i've added some additional logging to try to debug this. Can you uninstall and reinstall the component, restart hass, then try to login again? Let me know what error you get.

**Comment by echoz** [comment]
Huh interesting. I just updated the plugin to the current version (0.2?) after deleting the integration I have. Its now working fine and even found my grill!

**Comment by echoz** [comment]
Thanks for whatever you did!
