### ISSUE TITLE
Is there a way to bring this into HomeKit using HA?

### ISSUE THREAD

**Issue by AerioGit** [sebirdman/hass_traeger#34]
As far as I can tell, it isn't currently possible to bring the climate entity for the grill into HomeKit using the native HomeKit integration. Is this something that could be added in the future?

I'm honestly uncertain why it's not being brought over to HomeKit. I wonder if it has to do with the entity type?

Thanks for any help

**Comment by sebirdman** [comment]
@AerioGit Great question! i'm not really sure. This may be a home assistant question, i'm not sure of any reason why this integration wouldn't just transfer.

**Comment by AerioGit** [comment]
@sebirdman Thanks for the response! Yeah, it seems like it should just work, but the devices never show up. Will try to do a bit more research and see what I can find. Cheers

**Comment by PaRkThEcAr** [comment]
+1 for HomeKit support in Home Assistant. Looking over the logs, I have some logs for you @sebirdman!

`2022-01-30 15:04:34 ERROR (MainThread) [homeassistant.components.homekit] Failed to create a HomeKit accessory for climate.682719aec577_climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 615, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 222, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 139, in __init__
    super().__init__(*args, category=CATEGORY_THERMOSTAT)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 277, in __init__
    model=model[:MAX_MODEL_LENGTH],
TypeError: 'int' object is not subscriptable
2022-01-30 15:04:34 ERROR (MainThread) [homeassistant.components.homekit] Failed to create a HomeKit accessory for sensor.682719aec577_ambient_temperature
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 615, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 222, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_sensors.py", line 104, in __init__
    super().__init__(*args, category=CATEGORY_SENSOR)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 277, in __init__
    model=model[:MAX_MODEL_LENGTH],
TypeError: 'int' object is not subscriptable`

I tried to add 2 items (internal ambient temp and the thermostat or "climate" accessory)

Really any devices will return this error, but these are the two I would think would give some good information as to what home assistant is saying.

HW config: Raspberry Pi 4B 4gb running bullseye and a home assistant supervised install running core 2021.12.10

**Comment by njobrien1006** [comment]
For me, bringing the Climate Entities to HomeKit works fine. The sensors on the other hand, were a little odd. Ambient came in but refused to show on the iPhone main screen but, digging into the accessories it is indeed there. The Pellet Level % doesn't come in, presumably because it isn't supported by HomeKit unless it's % humidity.

 I'd suggest just bringing in the Climate and forgetting about .Ambient as it isn't nearly as accurate on the grills as .Climate.

![PNG image](https://user-images.githubusercontent.com/59174199/159076896-f6eef94f-e13c-40a5-9e00-f4e135151699.png)

**Comment by sebirdman** [comment]
@PaRkThEcAr i was having a similar issue a long while ago, i just got some time to sit down and look at it and...it's working fine on the latest HA like @njobrien1006's is. 

i think the bug was that the model for traeger is a number. feel free to re-open this issue if it's still broken for you on the latest HA

**Comment by PaRkThEcAr** [comment]
Ah yes! I've ran the latest for a hot minute and it seems to work! Thanks for the help!
