### ISSUE TITLE
Integration Unavailable

### ISSUE THREAD

**Issue by skrilla0** [sebirdman/hass_traeger#53]
Traeger Integration has been running rock solid until recently updating to HAOS  core-2022.7.3

Here is what is shown in the logs: 

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/traeger/__init__.py", line 57, in async_setup_entry
    await client.start(30)
  File "/config/custom_components/traeger/traeger.py", line 314, in start
    await self.update_grills()
  File "/config/custom_components/traeger/traeger.py", line 121, in update_grills
    json = await self.get_user_data()
  File "/config/custom_components/traeger/traeger.py", line 84, in get_user_data
    await self.refresh_token()
  File "/config/custom_components/traeger/traeger.py", line 80, in refresh_token
    self.token_expires = response["AuthenticationResult"]["ExpiresIn"] + request_time
TypeError: 'NoneType' object is not subscriptable```

Also seeing an issue when trying to access AWS: ```Timeout error fetching information from https://cognito-idp.us-west-2.amazonaws.com/ -```

**Comment by AaronAutomation** [comment]
I've had this same issue for awhile now and unfortunately have been unable to use this integration because of it.
